export const BUSINESS = {
  name: "Cabrita Café Garage",
  shortName: "Cabrita",
  tagline: "El garage de las mejores medialunas de Mendoza",
  description:
    "Café de especialidad, chipás artesanales y panadería recién horneada en el corazón del centro de Mendoza.",
  phone: "+542617176679",
  phoneDisplay: "+54 261 717-6679",
  instagram: "cabritacafegarage",
  instagramUrl: "https://instagram.com/cabritacafegarage",
  googleMapsUrl: "https://maps.google.com/?q=Cabrita+Garage+Café+Av+Belgrano+1184+Mendoza",
  pedidosYaUrl: "https://www.pedidosya.com.ar/restaurantes/mendoza/cabrita-garage-cafe",
  whatsappMessage: "¡Hola Cabrita! Quiero hacer un pedido 🥐☕",
} as const;

export const LOCATIONS = [
  {
    name: "Cabrita Café Garage — Belgrano",
    address: "Av. Belgrano 1184",
    city: "Ciudad de Mendoza",
    province: "Mendoza",
    zip: "M5500",
    coordinates: { lat: -32.8878, lng: -68.8497 },
    isVerified: true,
  },
  {
    name: "Cabrita Café Garage — Beltrán",
    address: "Beltrán y Juan B. Justo",
    city: "Mendoza",
    province: "Mendoza",
    coordinates: null,
    isVerified: false,
    note: "Dirección exacta no verificada",
  },
] as const;

export const SCHEDULE = {
  weekdays: { days: "Lunes a Viernes", hours: "09:00 – 20:30" },
  saturday: { days: "Sábado", hours: "09:00 – 14:00" },
  sunday: { days: "Domingo", hours: "09:00 – 14:00" },
} as const;

export const PRODUCTS = [
  {
    id: "medialunas",
    name: "Medialunas",
    description: "Hojaldradas, doradas y recién horneadas. Las favoritas de Mendoza. Un ícono que tenés que probar sí o sí.",
    badge: "⭐ Favoritas",
    image: null,
  },
  {
    id: "chipas",
    name: "Chipás",
    description: "Pão de queijo artesanal. Ideales para compartir (o para vos solo). Probá el de Roquefort o lomito ahumado.",
    badge: "⭐ Imperdibles",
    image: null,
  },
  {
    id: "cafe",
    name: "Café de Especialidad",
    description: "Desde un espresso potente hasta un flat white cremoso. 29 variedades para todos los gustos.",
    badge: "☕ Especialidad",
    image: null,
  },
  {
    id: "alfajor",
    name: "Alfajor de Pistacho",
    description: "Alfajor artesanal con pistacho. La joya de nuestra pastelería, perfecto para acompañar tu café.",
    badge: "🥇 Top",
    image: null,
  },
  {
    id: "cookies",
    name: "Cookies",
    description: "Tres variedades: chocolate brownie, chocolate clásica y pistacho. Crocantes por fuera, suaves por dentro.",
    badge: "🍪 Variedad",
    image: null,
  },
] as const;

export const MENU_CATEGORIES = [
  {
    id: "cafes",
    name: "Cafés",
    items: [
      { name: "Espresso", description: "Café de especialidad en su forma más pura.", price: "$3.400" },
      { name: "Doble Espresso", description: "Doble shot para los que necesitan más.", price: "$4.200" },
      { name: "Espresso Macchiato", description: "Espresso con un toque de espuma de leche.", price: "$3.500" },
      { name: "Long Black 2 shots", description: "Intenso y suave, ideal para arrancar el día.", price: "$4.800" },
      { name: "Long Black 4 shots", description: "Dosis extra para los valientes.", price: "$5.500" },
      { name: "Americano Mediano", description: "Clásico americano de especialidad.", price: "$3.800" },
      { name: "Cortado Chico", description: "Pocillo de espresso con un velo de leche.", price: "$4.000" },
      { name: "Cortado Mediano", description: "Más grande, mismo sabor.", price: "$4.500" },
      { name: "Capuchino Mediano", description: "El clásico espumoso que nunca falla.", price: "$4.900" },
      { name: "Capuchino Grande", description: "Capuchino en versión generosa.", price: "$5.200" },
      { name: "Latte Mediano", description: "Suave y cremoso, ideal para cualquier momento.", price: "$4.500" },
      { name: "Latte Grande", description: "Más café, más cremosidad.", price: "$4.800" },
      { name: "Flat White Mediano", description: "Doble shot con microespuma aterciopelada.", price: "$5.000" },
      { name: "Flat White Grande", description: "Flat white en tamaño grande.", price: "$5.300" },
      { name: "Flat White 3 shots", description: "Para los que quieren vuelo.", price: "$6.000" },
      { name: "Caramel Latte Mediano", description: "Latte con el toque dulce del caramelo.", price: "$4.800" },
      { name: "Caramel Latte Grande", description: "Caramel latte bien grande.", price: "$5.100" },
      { name: "Vainilla Latte Mediano", description: "Latte con el aroma inconfundible de la vainilla.", price: "$4.800" },
      { name: "Vainilla Latte Grande", description: "Vainilla latte tamaño grande.", price: "$5.100" },
      { name: "Coldbrew", description: "Extracción en frío 24hs. Suave, dulce natural, sin amargor.", price: "$4.500" },
      { name: "Espresso Tonic 2 shots", description: "Refrescante y con personalidad.", price: "$5.400" },
      { name: "Ice Latte", description: "Latte frío para los días de calor.", price: "$4.900" },
      { name: "Ice Latte vainilla / caramelo", description: "Latte frío con el sabor que elijas.", price: "$5.500" },
      { name: "Chocolate Mediano", description: "Chocolate caliente cremoso.", price: "$4.000" },
      { name: "Chocolate Grande", description: "Chocolate caliente en versión XL.", price: "$4.200" },
      { name: "Chai Latte Grande", description: "Té chai especiado con leche cremosa.", price: "$4.400" },
      { name: "Ice Chai Latte", description: "Chai latte frío, perfecto para el verano.", price: "$4.500" },
      { name: "Té Chai", description: "Té chai especiado bien tradicional.", price: "$4.000" },
    ],
  },
  {
    id: "bebidas",
    name: "Bebidas",
    items: [
      { name: "Vermú Éxtasis", description: "Vermut artesanal.", price: "$4.500" },
      { name: "Gin Tónic", description: "Clásico gin tonic.", price: "$4.800" },
      { name: "Sprite", description: "Gaseosa sprite.", price: "$1.800" },
      { name: "Agua con Gas", description: "Agua mineral con gas.", price: "$2.000" },
      { name: "Agua mineral sin gas", description: "Agua mineral natural.", price: "$2.000" },
      { name: "Jugo de naranja CHICO", description: "Jugo de naranja exprimido chico.", price: "$3.000" },
      { name: "Coca 500ml", description: "Coca-Cola clásica 500ml.", price: "$2.500" },
      { name: "Jugo Estancia Los", description: "Jugo de estancia.", price: "$5.000" },
    ],
  },
  {
    id: "otros",
    name: "Otros",
    items: [
      { name: "Jugo de Naranja Grande", description: "Jugo de naranja exprimido grande.", price: "$5.000" },
      { name: "Limonada", description: "Limonada natural bien refrescante.", price: "$4.000" },
      { name: "Ice Tea", description: "Té frío del día.", price: "$4.000" },
      { name: "Licuado", description: "Licuado de frutas natural.", price: "$4.800" },
      { name: "Prensa 600ml", description: "Jugo prensado en frío 600ml.", price: "$7.000" },
      { name: "Yogurt fruta y granola", description: "Yogurt natural con fruta fresca y granola de la casa.", price: "$7.000" },
    ],
  },
  {
    id: "extras",
    name: "Extras / Agregados",
    items: [
      { name: "Extra Leche de almendras", description: "Sustitución por leche de almendras.", price: "$1.400" },
      { name: "Extra Leche Deslactosada", description: "Sustitución por leche deslactosada.", price: "$500" },
      { name: "Extra Café", description: "Shot extra de café.", price: "$300" },
    ],
  },
  {
    id: "promos",
    name: "Promos Cafetería",
    items: [
      { name: "Café mediano + 2 Medialunas", description: "La clásica, la de siempre. Perfecta.", price: "$7.500" },
      { name: "Café mediano + 2 Chipá", description: "Café y chipá, la combinación que enamora.", price: "$7.000" },
      { name: "Café mediano + Budín Banana", description: "Dulce y cremoso, ideal para media mañana.", price: "$7.000" },
      { name: "Café mediano + 2 tortitas", description: "Liviano y rico, para arranque suave.", price: "$5.500" },
      { name: "Café mediano + cookie", description: "Café + cookie, el maridaje perfecto.", price: "$6.500" },
      { name: "Café mediano + tostadito + jugo naranja chico", description: "Desayuno completo, el que lo tiene todo.", price: "$9.000" },
    ],
  },
  {
    id: "panaderia",
    name: "Panadería",
    items: [
      { name: "Chipá", description: "Pão de queijo artesanal. Ideal para compartir (o no).", price: "$1.300" },
      { name: "Chipá con Salame", description: "Chipá artesanal con salame.", price: "$1.300" },
      { name: "Chipá con Hongos", description: "Chipá artesanal con hongos.", price: "$1.300" },
      { name: "Chipá con Lomito ahumado", description: "Chipá artesanal con lomito ahumado.", price: "$1.300" },
      { name: "Chipá con Roquefort", description: "Chipá artesanal con roquefort. Una bomba.", price: "$1.300" },
      { name: "Chipá sandwich jamón y queso", description: "Chipá grande relleno de jamón y queso.", price: "$6.000" },
      { name: "Media docena Chipá tradicional", description: "6 chipás tradicionales.", price: "$7.500" },
      { name: "Docena Chipá tradicional", description: "12 chipás tradicionales.", price: "$15.000" },
      { name: "Media docena Chipá surtido", description: "6 chipás variados.", price: "$7.500" },
      { name: "Docena Chipá surtido", description: "12 chipás variados.", price: "$15.000" },
      { name: "Medialuna", description: "Hojaldrada, dorada, recién horneada. Nuestro ícono.", price: "$2.000" },
      { name: "Medialuna jamón y queso", description: "Medialuna gigante rellena de jamón y queso.", price: "$3.500" },
      { name: "Tortita con romero", description: "Tortita de la casa con romero.", price: "$800" },
      { name: "Tortita con jamón y queso", description: "Tortita rellena de jamón y queso.", price: "$2.000" },
      { name: "Ciabatta", description: "Pan de masa madre italiano.", price: "$1.400" },
      { name: "Baguette", description: "Baguette artesanal crujiente.", price: "$1.100" },
      { name: "Focaccia", description: "Focaccia artesanal de la casa.", price: "$7.000" },
      { name: "Media Focaccia", description: "Media focaccia, justa para uno.", price: "$3.000" },
      { name: "Focaccia XL", description: "Focaccia tamaño XXL para compartir.", price: "$30.000" },
      { name: "Focaccia Hongos Vegan", description: "Focaccia vegana con hongos.", price: "$7.000" },
      { name: "Prepizza", description: "Base de pizza lista para hornear.", price: "$1.900" },
      { name: "Bollo de Pizza Crudo", description: "Bollo de pizza artesanal crudo.", price: "$1.800" },
      { name: "Pan de Campo 900gr", description: "Pan de campo rústico 900gr.", price: "$4.500" },
      { name: "Pan semillas 900gr", description: "Pan con semillas 900gr.", price: "$6.500" },
      { name: "Pan de zapallo", description: "Pan artesanal de zapallo.", price: "$5.500" },
      { name: "Pan Lactal", description: "Pan lactal artesanal.", price: "$7.000" },
      { name: "Pan Dulce", description: "Pan dulce artesanal.", price: "$8.000" },
      { name: "Pan de Chocolate", description: "Pan artesanal con chocolate.", price: "$3.500" },
      { name: "Pan 100% Integral", description: "Pan integral 100% harina integral.", price: "$7.500" },
      { name: "Pan con pasas y romero 1,5kg", description: "Pan grande con pasas y romero.", price: "$6.000" },
      { name: "Rosca de Pascua", description: "Rosca artesanal de pascua.", price: "$15.000" },
      { name: "Scon de queso Keto", description: "Scon de queso bajo en carbohidratos.", price: "$5.000" },
      { name: "Croissant", description: "Croissant de manteca, laminado, perfecto.", price: "$2.800" },
      { name: "Palmerita", description: "Palmerita hojaldrada.", price: "$1.100" },
      { name: "Fosforito", description: "Fosforito artesanal.", price: "$3.500" },
      { name: "Danesa", description: "Danesa artesanal hojaldrada.", price: "$3.500" },
      { name: "Pebete", description: "Pebete artesanal.", price: "$950" },
      { name: "Principal Brioche 60gr", description: "Pan brioche artesanal 60gr.", price: "$690" },
      { name: "Principal nuez y romero 90gr", description: "Pan con nuez y romero 90gr.", price: "$470" },
      { name: "Rosetta Campo x 250gr", description: "Rosetta de campo 250gr.", price: "$1.000" },
      { name: "Roll de Canela", description: "Rol de canela esponjoso con glaseado.", price: "$3.400" },
      { name: "Roll de Pistacho", description: "Rol de pistacho con crema de pistacho.", price: "$3.000" },
    ],
  },
  {
    id: "sandwiches",
    name: "Sandwiches & Tostados",
    items: [
      { name: "Tostado Jamón y Queso", description: "En masa madre. El clásico perfecto.", price: "$6.000" },
      { name: "Medio tostado jamón y queso", description: "La mitad del clásico.", price: "$4.000" },
      { name: "Tostado J y Q con tomate y oliva", description: "Tostado con tomate y aceite de oliva.", price: "$7.000" },
      { name: "Sandwich de Jamón Crudo, roquefort y rúcula", description: "Pan artesanal, jamón crudo, roquefort y rúcula.", price: "$8.000" },
      { name: "Sandwich mortadela, stracciatella y rúcula", description: "Mortadela, stracciatella y rúcula.", price: "$7.500" },
      { name: "Sandwich Vermutarde Pollo", description: "Sandwich especial vermutarde de pollo.", price: "$6.000" },
      { name: "Sandwich Vermutarde L", description: "Sandwich especial vermutarde.", price: "$6.000" },
      { name: "Sandwich Vermutarde Vegan", description: "Sandwich vermutarde vegano.", price: "$6.000" },
      { name: "Sandwich Vegan Hongos", description: "Para compartir. Hongos y verduras.", price: "$7.500" },
      { name: "Avocado dos tostones", description: "Dos tostadas con palta y toppings.", price: "$9.000" },
      { name: "Avocado en Pan de chipa", description: "Palta fresca sobre pan de chipá artesanal.", price: "$7.500" },
      { name: "Avocado en Medialuna", description: "Nuestra medialuna estrella con palta.", price: "$6.000" },
      { name: "Bagel lomito cheddar y huevo", description: "Bagel artesanal con lomito, cheddar fundido y huevo.", price: "$7.000" },
    ],
  },
  {
    id: "pasteleria",
    name: "Pastelería",
    items: [
      { name: "Cookie chocolate brownie", description: "Intensa, húmeda, irresistible.", price: "$3.000" },
      { name: "Cookie Chocolate", description: "La clásica de siempre.", price: "$3.100" },
      { name: "Cookie de Pistacho", description: "Sutil, elegante, con pistacho.", price: "$2.900" },
      { name: "Budín banana", description: "Húmedo y con el dulzor justo de la banana.", price: "$3.800" },
      { name: "Budín de Limón", description: "Cítrico, fresco, glaseado.", price: "$3.800" },
      { name: "Carrot Budín", description: "Especiado y con trocitos de nuez.", price: "$3.800" },
      { name: "Babka", description: "Trenzada de chocolate y canela.", price: "$3.200" },
      { name: "Muffins arándanos", description: "Esponjosos con arándanos naturales.", price: "$3.800" },
      { name: "Muffins DDL y Pistacho", description: "Dulce de leche y pistacho.", price: "$3.400" },
      { name: "Tartitas de limón", description: "Base quebrada con crema de limón.", price: "$3.000" },
      { name: "Blondie de Pistacho", description: "El hermano rubio del brownie.", price: "$6.000" },
      { name: "Alfajor de Pistacho", description: "Alfajor artesanal con pistacho.", price: "$6.000" },
      { name: "Alfajor de maní", description: "Clásico argentino con maní.", price: "$3.000" },
      { name: "Alfajor de Maicena", description: "El tradicional, con maicena y dulce de leche.", price: "$4.000" },
      { name: "Avocado toast", description: "Una tostada con palta y toppings.", price: "$5.500" },
      { name: "Roll NY", description: "Estilo Nueva York, cremoso.", price: "$1.200" },
    ],
  },
  {
    id: "mayorista",
    name: "Mayorista",
    items: [
      { name: "Chipá", description: "Precio por unidad.", price: "$1.050" },
      { name: "Medialuna", description: "Precio por unidad.", price: "$1.100" },
      { name: "Medialuna Cocinada", description: "Precio por unidad.", price: "$1.300" },
      { name: "Tortita", description: "Precio por unidad.", price: "$470" },
      { name: "Ciabatta", description: "Precio por unidad.", price: "$800" },
      { name: "Baguetín", description: "Precio por unidad.", price: "$750" },
      { name: "Campo de molde", description: "Precio por unidad.", price: "$3.000" },
      { name: "Campo 1,25kg", description: "Precio por unidad.", price: "$4.000" },
      { name: "Pan de Campo", description: "Precio por unidad.", price: "$3.600" },
      { name: "Pan semillas", description: "Precio por unidad.", price: "$4.600" },
      { name: "Pan Lactal", description: "Precio por unidad.", price: "$5.500" },
      { name: "Focaccia 1kg", description: "Precio por unidad.", price: "$5.500" },
      { name: "Prepizza", description: "Precio por unidad.", price: "$1.150" },
      { name: "Pan 100% integral", description: "Precio por unidad.", price: "$5.100" },
      { name: "Pan de Chocolate", description: "Precio por unidad.", price: "$2.000" },
      { name: "Croissant 115gr", description: "Precio por unidad.", price: "$1.200" },
      { name: "Roll de Canela", description: "Precio por unidad.", price: "$1.450" },
      { name: "Roll NY", description: "Precio por unidad.", price: "$400" },
      { name: "Danesa", description: "Precio por unidad.", price: "$1.100" },
      { name: "Danesa Cocinada", description: "Precio por unidad.", price: "$1.500" },
      { name: "Fosforito", description: "Precio por unidad.", price: "$1.100" },
      { name: "Palmerita", description: "Precio por unidad.", price: "$550" },
      { name: "Bagel", description: "Precio por unidad.", price: "$1.300" },
      { name: "Pionono", description: "Precio por unidad.", price: "$821" },
      { name: "Granola x 1kg", description: "Precio por unidad.", price: "$40.000" },
      { name: "Cookie", description: "Precio por unidad (pastelería mayorista).", price: "$2.200" },
      { name: "Budín", description: "Precio por unidad (pastelería mayorista).", price: "$1.500" },
      { name: "Alfajor Pistacho", description: "Precio por unidad (pastelería mayorista).", price: "$4.900" },
      { name: "Scon Keto Parmesano", description: "Precio por unidad (pastelería mayorista).", price: "$4.500" },
      { name: "Pan de Chipa", description: "Precio por unidad (pastelería mayorista).", price: "$2.100" },
    ],
  },
] as const;

export const REVIEWS = [
  {
    text: "Las mejores medialunas de Mendoza. El lugar es chiquito pero el sabor es gigante. Imperdible.",
    author: "Wanderlog",
    rating: 5,
  },
  {
    text: "Los chipás son los mejores de la ciudad, especialmente el de Roquefort. La atención es increíble.",
    author: "InMendoza",
    rating: 5,
  },
  {
    text: "Excelente café de especialidad. El personal te recomienda con tanto amor que querés probar todo.",
    author: "Google Reviews",
    rating: 5,
  },
  {
    text: "Un garaje convertido en el lugar más acogedor para desayunar. La vereda tiene nombre propio.",
    author: "TripAdvisor",
    rating: 5,
  },
  {
    text: "Tienen opciones veganas riquísimas. Las cookies y brownies son espectaculares.",
    author: "HappyCow",
    rating: 5,
  },
  {
    text: "El cinnamon roll es MUST. El café de especialidad muy bien ejecutado. Volvemos cada vez que venimos a Mendoza.",
    author: "Wanderlog",
    rating: 5,
  },
] as const;

export const FAQS = [
  {
    q: "¿Dónde queda Cabrita Café Garage?",
    a: "Estamos en Av. Belgrano 1184, Ciudad de Mendoza. También tenemos sucursal en Beltrán y Juan B. Justo.",
  },
  {
    q: "¿Cuáles son sus horarios?",
    a: "Lunes a viernes de 09:00 a 20:30 hs. Sábados y domingos de 09:00 a 14:00 hs.",
  },
  {
    q: "¿Tienen opciones veganas?",
    a: "Tenemos opciones veganas disponibles. Consultanos por WhatsApp para conocer la variedad del día.",
  },
  {
    q: "¿Qué producto no puedo dejar de probar?",
    a: "Nuestras medialunas y los chipás (especialmente el de Roquefort) son los favoritos de la casa.",
  },
  {
    q: "¿Hacen delivery?",
    a: "Sí, podés pedir por PedidosYa o escribirnos por WhatsApp para retiro o envío.",
  },
  {
    q: "¿Puedo sentarme a consumir en el local?",
    a: "El espacio es pequeño y estilo garage, ideal para take-away. Pero tenemos vereda para disfrutar sin apuro.",
  },
  {
    q: "¿Aceptan mascotas?",
    a: "Sí, somos pet-friendly en la vereda. Traé a tu compañero de cuatro patas.",
  },
  {
    q: "¿Tienen menú para eventos o pedidos grandes?",
    a: "Consultá por WhatsApp para coordinar pedidos especiales, eventos y pedidos por mayor.",
  },
  {
    q: "¿Venden por mayor?",
    a: "Sí, tenemos línea mayorista con precios por unidad. Escribinos por WhatsApp para más información.",
  },
  {
    q: "¿Tienen wifi o espacio de trabajo?",
    a: "El local es pequeño y enfocado en take-away. No es un espacio de coworking.",
  },
  {
    q: "¿Cómo puedo dejar una reseña?",
    a: "Buscá 'Cabrita Café Garage' en Google y dejá tu opinión. ¡Nos ayuda un montón!",
  },
] as const;

export const EVENTS = [
  {
    title: "Vermutarde en Cabrita",
    description:
      "Evento de vermut, música y buena onda. Seguinos en Instagram para conocer las próximas fechas.",
    date: "Próximamente",
    image: null,
  },
  {
    title: "Pop-ups & Lanzamientos",
    description:
      "Participamos de la escena cafetalera local con colaboraciones y ediciones limitadas.",
    date: "Todo el año",
    image: null,
  },
] as const;
